version: '3'
services:
    postgres:
        container_name: huz_postgres
        environment:
            - POSTGRES_DB=huz
            - POSTGRES_USER=huzer
        image: 'postgres:11'
        ports:
            - '5432:5432'
    main:
        container_name: huz_main
        build: .
#        depends_on:
#            - postgres
