version: '3'
services:
  grafana:
    container_name: huz_grafana
    depends_on:
      - main
      - postgres
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    volumes:
      - <huz-path>/grafana/datasources:/etc/grafana/provisioning/datasources
      - <huz-path>/grafana/dashboards:/etc/grafana/provisioning/dashboards
  main:
    command: bash -c '/etc/init.d/cron start; wait; tail -f /dev/null'
    container_name: huz_main
    build: .
    depends_on:
      - postgres
    volumes:
      - <huz-path>:/huz
#      - <huz-path>:/huz/src
  postgres:
    container_name: huz_postgres
    environment:
      - POSTGRES_DB=huz
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=huzer
    image: 'postgres:11'
    ports:
      - '5432:5432'
    volumes:
      - <huz-path>:/huz
      - <huz-path>/postgres/data:/var/lib/postgresql/data
